Repository himanshusharma89/relic_bazaar, pull requests merged in 2021-05, with the labels that each got.

#220 Fixes #217
  lib/dashboard.dart
Labels: GSSOC21, Level1

#224 Added show and hide password functionality
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
  lib/widgets/text_field_decoration.dart
Labels: GSSOC21, Level1

#218 Fix: Issue #103, Added SafeArea in the the entire app
  lib/main.dart
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
  lib/views/change_username_password.dart
  lib/views/home_view.dart
  lib/views/profile/orders.dart
  lib/views/profile/settings/faqs_screen.dart
  lib/views/profile/settings/github_webview.dart
  lib/views/profile/settings/manage_address.dart
  lib/views/profile/wishlist.dart
  lib/widgets/payment/payment_successful.dart
  lib/widgets/product/product_page.dart
Labels: GSSOC21, Level1

#225 Fix: Breaking code fixed
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
Labels: GSSOC21, Level0, bug

#227 Fixes #226
  lib/helpers/constants.dart
  lib/helpers/product_search_delegate.dart
  lib/model/product_model.dart
  lib/services/product_service.dart
  lib/views/home_view.dart
  pubspec.yaml
Labels: GSSOC21, Level2

#231 Fixes #230
  lib/helpers/constants.dart
  lib/helpers/route_page.dart
  lib/main.dart
  lib/services/auth_service.dart
  lib/views/get_user_details_view.dart
Labels: GSSOC21

#232 Fixes #228
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
Labels: GSSOC21, Level1

#234 Fixes #233
  lib/views/auth/signup_view.dart
Labels: GSSOC21, Level1

#236 Fixes #235
  lib/services/auth_service.dart
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
Labels: GSSOC21

#237 Fixes #177
  lib/helpers/input_validators.dart
  lib/services/auth_service.dart
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
  lib/widgets/show_error_dialog.dart
Labels: GSSOC21, Level3

#239 Fixes #238
  lib/helpers/input_validators.dart
  lib/helpers/route_page.dart
  lib/main.dart
  lib/model/user_model.dart
  lib/services/auth_service.dart
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
  lib/views/get_user_details_view.dart
Labels: GSSOC21, Level3

#242 Fixes #241
  lib/helpers/route_page.dart
  lib/services/auth_service.dart
  lib/views/auth/signup_view.dart
  lib/views/get_user_details_view.dart
Labels: GSSOC21

#243 Fixes #240
  lib/dashboard.dart
  lib/helpers/route_page.dart
  lib/main.dart
  lib/model/user_model.dart
  lib/services/auth_service.dart
  lib/services/cloud_storage_service.dart
  lib/services/db_userdata.dart
  lib/services/product_service.dart
  lib/views/auth/signup_view.dart
  lib/views/get_user_details_view.dart
  lib/views/home_view.dart
  lib/views/profile/profile_view.dart
  pubspec.yaml
Labels: GSSOC21, Level3

#245 Fixes #244
  lib/services/auth_service.dart
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
Labels: GSSOC21

#247 Fixes #246
  lib/views/profile/profile_view.dart
  pubspec.yaml
Labels: GSSOC21, Level1
