Repository himanshusharma89/relic_bazaar, pull requests merged in 2021-03, with the labels that each got.

#71 Add linting using lint package
  analysis_options.yaml
  lib/dashboard.dart
  lib/helpers/app_icons.dart
  lib/helpers/constants.dart
  lib/helpers/slide_route.dart
  lib/main.dart
  lib/views/cart.dart
  lib/views/home.dart
  lib/views/profile.dart
  lib/views/search.dart
  lib/widgets/bottom_nav_bar.dart
  lib/widgets/payment/cart_item.dart
  lib/widgets/payment/order_item.dart
  lib/widgets/payment/payment_successful.dart
  lib/widgets/payment/payment_window.dart
  lib/widgets/product/product_card.dart
  lib/widgets/product/product_page.dart
  lib/widgets/retro_button.dart
  lib/widgets/splash.dart
  pubspec.yaml
Labels: GSSOC'21, Intermediate

#80 added Greeting bot
  .github/config.yml
Labels: GSSOC21, Level1

#81 removed leading search icon on home screen Search Bar
  lib/views/home.dart
Labels: GSSOC21, Level1

#82 Implemented a better way to hide the keyboard properly
  lib/main.dart
Labels: GSSOC21, Level1

#90 added product model
  lib/model/product.dart
Labels: GSSOC21, Level2

#92 made profile screen responsive for small screen size
  lib/widgets/payment/order_item.dart
Labels: GSSOC21, Level1

#102 Outsourced Drawer and Drawer Item widgets
  lib/model/product.dart
  lib/views/drawer_widget.dart
  lib/views/home.dart
  lib/widgets/drawer_item.dart
Labels: GSSOC21, Level2

#97 Added menu icon to the top right to navigate to the "Settings" screen
  lib/views/profile.dart
  lib/views/settings.dart
Labels: GSSOC21, Level1

#88 docs: added pr label workflow
  .github/workflows/pr_label.yml
Labels: Level1

#113 fixes #105 profile screen and settings screen bug fixed
  lib/views/profile.dart
  lib/views/settings.dart
Labels: GSSOC21, Level0

#114 Removed scroll glow
  lib/main.dart
Labels: GSSOC21, Level1

#117 Made Settings layout
  lib/views/settings.dart
Labels: GSSOC21, Level2

#104 Added widget tests
  test/widget_test.dart
Labels: GSSOC21, Level3

#116 Package Name change
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/retro_shopping/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
Labels: GSSOC21, Level3

#124 Issue-118 Correction in Readme.md
  README.md
Labels: GSSOC21, Level0

#127 Order model creation
  lib/model/order.dart
Labels: GSSOC21, Level2

#123 Home Screen Updated
  lib/views/home.dart
Labels: GSSOC21

#129 'Wishlist-Screen'
  lib/views/Wishlist.dart
  lib/views/drawer_widget.dart
Labels: GSSOC21, Level2

#130 Created about page
  lib/views/about.dart
  pubspec.yaml
Labels: GSSOC21, Level1

#131 Fixed the Renderflex Overflow issue
  lib/views/cart.dart
  lib/widgets/payment/cart_item.dart
  lib/widgets/payment/payment_window.dart
Labels: GSSOC21, Level2

#126 AdMob Integration
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  pubspec.yaml
Labels: GSSOC21, Level2

#132 Order Screen
  lib/views/drawer_widget.dart
  lib/views/orders.dart
  lib/views/settings.dart
Labels: GSSOC21, Level2

#136 Fix : Issue 101
  lib/helpers/constants.dart
  lib/widgets/product/product_card.dart
Labels: GSSOC21, Level1

#137 issue #38 made manage address screen
  lib/model/address.dart
  lib/views/address_screen.dart
  lib/views/manage_address.dart
  lib/views/profile.dart
  lib/views/settings.dart
  pubspec.yaml
Labels: GSSOC21

#139 Ported to Native splash screen
  android/app/src/main/res/drawable/background.png
  android/app/src/main/res/drawable/launch_background.xml
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  ios/Runner/Base.lproj/LaunchScreen.storyboard
  lib/helpers/route_page.dart
  lib/main.dart
  lib/widgets/splash.dart
Labels: GSSOC21, Level2

#140 added ads on dashboard and product page
  lib/dashboard.dart
  lib/helpers/ad_state.dart
  lib/main.dart
  lib/widgets/product/product_page.dart
  pubspec.yaml
Labels: GSSOC21, Level2

#145 Update README.md
  README.md
Labels: GSSOC21, Level0

#142 added code for faqs screen
  assets/FAQ.pdf
  lib/views/faqs_screen.dart
  lib/views/settings.dart
  pubspec.yaml
Labels: GSSOC21, Level2

#144 Added login screen(with all the resolved changes)
  assets/items/fb.png
  assets/items/google.png
  lib/dashboard.dart
  lib/main.dart
  lib/views/login.dart
Labels: GSSOC21, Level1

#146 Added google signin(#27)
  lib/services/google_auth.dart
  lib/views/drawer.dart
  lib/views/login.dart
  pubspec.yaml
Labels: GSSOC21, Level3

#148 Added SignUp Screen
  lib/views/login.dart
  lib/views/signup.dart
Labels: GSSOC21, Level1

#149 fix: bump flutter version in the app release action
  .github/workflows/android-release.yml
Labels: GSSOC21, Level2

#154 Fixed Issue #151
  lib/dashboard.dart
  lib/helpers/constants.dart
  lib/helpers/route_page.dart
  lib/main.dart
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
  lib/views/cart_view.dart
  lib/views/drawer_view.dart
  lib/views/home_view.dart
  lib/views/profile/profile_view.dart
  lib/views/profile/settings/address_screen.dart
  lib/views/profile/settings/manage_address.dart
  lib/views/profile/settings/settings_view.dart
  lib/widgets/payment/payment_window.dart
  lib/widgets/product/product_card.dart
  lib/widgets/product/product_page.dart
  lib/widgets/settings_item.dart
  test/widget_test.dart
Labels: GSSOC21, Level2

#156 Added batches on top in Readme.md file
  README.md
Labels: GSSOC21, Level1

#150 Added the change username and password screen
  lib/helpers/constants.dart
  lib/helpers/route_page.dart
  lib/views/change_username_password.dart
  lib/views/profile/settings/settings_view.dart
Labels: GSSOC21, Level2

#159 Added T&C Screen Issue #38
  lib/helpers/constants.dart
  lib/helpers/route_page.dart
  lib/main.dart
  lib/views/profile/settings/settings_view.dart
  lib/views/terms_conditions_view.dart
Labels: GSSOC21, Level2

#162 Added Email Auth #27
  lib/services/auth_service.dart
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
  lib/views/drawer_view.dart
Labels: GSSOC21, Level3

#163 Added Unknown Screen. Fixes Issue #161
  lib/helpers/route_page.dart
  lib/views/unknown_view.dart
Labels: GSSOC21, Level1

#160 Integrate Remote Config #48
  lib/main.dart
  lib/services/remote_config.dart
  pubspec.yaml
Labels: GSSOC21, Level2

#171 Overflow Problem in Settings Page
  android/app/build.gradle
  android/build.gradle
  lib/views/profile/settings/settings_view.dart
  lib/widgets/settings_item.dart
Labels: GSSOC21, Level1

#173 Fixed Issues in Cart Screen.
  lib/views/cart_view.dart
Labels: GSSOC21, Level1

#107 README.md file enhanced
  README.md
Labels: GSSOC21, Level0
