Repository himanshusharma89/relic_bazaar, pull requests merged in 2021-04, with the labels that each got.

#170 Login UI Update
  lib/views/auth/login_view.dart
Labels: GSSOC21, Level1

#172 Added in app web view for github repository link
  lib/helpers/constants.dart
  lib/helpers/route_page.dart
  lib/views/profile/settings/github_webview.dart
  lib/views/profile/settings/settings_view.dart
  pubspec.yaml
Labels: GSSOC21, Level2

#179 Used FocusNode to shift from one TextFormField to another
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
  lib/views/change_username_password.dart
Labels: GSSOC21, Level2

#176 Made Logout button functional in Settings screen. Fixes #38
  lib/services/auth_service.dart
  lib/views/drawer_view.dart
  lib/views/profile/settings/settings_view.dart
  lib/widgets/drawer_item.dart
  lib/widgets/settings_item.dart
Labels: GSSOC21

#181 Keep User Logged In
  lib/main.dart
Labels: GSSOC21

#185 Fixes Issue #183. Added Privacy Policy Screen.
  lib/helpers/constants.dart
  lib/helpers/route_page.dart
  lib/views/profile/settings/privacy_policy_screen.dart
  lib/views/profile/settings/settings_view.dart
  pubspec.yaml
Labels: GSSOC21, Level2

#184 added notificationsScreen
  lib/helpers/constants.dart
  lib/helpers/route_page.dart
  lib/views/profile/settings/notifications_toggle.dart
  lib/views/profile/settings/settings_view.dart
Labels: GSSOC21, Level2

#188 fixed renderflex error
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
Labels: GSSOC21, Level1

#191 Fixes #190
  lib/services/product_service.dart
  lib/views/home_view.dart
Labels: GSSOC21, Level2

#195 Fixes #55. Pushing gh-pages
  404.html
  assets/images/favicon.png
  assets/javascripts/bundle.7353b375.min.js
  assets/javascripts/bundle.7353b375.min.js.map
  assets/javascripts/lunr/min/lunr.ar.min.js
  assets/javascripts/lunr/min/lunr.da.min.js
  assets/javascripts/lunr/min/lunr.de.min.js
  assets/javascripts/lunr/min/lunr.du.min.js
  assets/javascripts/lunr/min/lunr.es.min.js
  assets/javascripts/lunr/min/lunr.fi.min.js
  assets/javascripts/lunr/min/lunr.fr.min.js
  assets/javascripts/lunr/min/lunr.hu.min.js
  assets/javascripts/lunr/min/lunr.it.min.js
  assets/javascripts/lunr/min/lunr.ja.min.js
  assets/javascripts/lunr/min/lunr.jp.min.js
  assets/javascripts/lunr/min/lunr.multi.min.js
  assets/javascripts/lunr/min/lunr.nl.min.js
  assets/javascripts/lunr/min/lunr.no.min.js
  assets/javascripts/lunr/min/lunr.pt.min.js
  assets/javascripts/lunr/min/lunr.ro.min.js
  assets/javascripts/lunr/min/lunr.ru.min.js
  assets/javascripts/lunr/min/lunr.stemmer.support.min.js
  assets/javascripts/lunr/min/lunr.sv.min.js
  assets/javascripts/lunr/min/lunr.tr.min.js
  assets/javascripts/lunr/min/lunr.vi.min.js
  assets/javascripts/lunr/tinyseg.js
  assets/javascripts/workers/search.fe42c31b.min.js
  assets/javascripts/workers/search.fe42c31b.min.js.map
  assets/stylesheets/main.9299cb39.min.css
  assets/stylesheets/main.9299cb39.min.css.map
  assets/stylesheets/palette.ef6f36e2.min.css
  assets/stylesheets/palette.ef6f36e2.min.css.map
  docs/index.md
  docs/our_solution.md
  images/promo.png
  index.html
  mkdocs.yml
  our_solution/index.html
  search/search_index.json
  sitemap.xml
  sitemap.xml.gz
Labels: GSSOC21, Level2

#198 Fixes #197
  lib/widgets/payment/payment_successful.dart
Labels: GSSOC21, Level1

#200 added userinfo to firebase
  lib/services/auth_service.dart
  pubspec.yaml
Labels: GSSOC21, Level1

#202 added loader
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
  pubspec.yaml
Labels: GSSOC21, Level1

#203 Fixes #199
  lib/widgets/product/product_page.dart
Labels: GSSOC21, Level1

#204 Fixes #25
  lib/helpers/product_search_delegate.dart
  lib/views/home_view.dart
  lib/views/search_view.dart
  lib/widgets/search_bar.dart
Labels: GSSOC21, Level2

#208 Package name changed successfully
  android/app/google-services.json
  android/app/src/main/kotlin/tech/himanshusharma/relic_bazaar/MainActivity.kt
  ios/Runner/Info.plist
  lib/dashboard.dart
  lib/helpers/constants.dart
  lib/helpers/product_search_delegate.dart
  lib/helpers/route_page.dart
  lib/main.dart
  lib/services/auth_service.dart
  lib/services/product_service.dart
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
  lib/views/cart_view.dart
  lib/views/change_username_password.dart
  lib/views/drawer_view.dart
  lib/views/home_view.dart
  lib/views/profile/orders.dart
  lib/views/profile/profile_view.dart
  lib/views/profile/settings/about.dart
  lib/views/profile/settings/address_screen.dart
  lib/views/profile/settings/faqs_screen.dart
  lib/views/profile/settings/github_webview.dart
  lib/views/profile/settings/manage_address.dart
  lib/views/profile/settings/notifications_toggle.dart
  lib/views/profile/settings/privacy_policy_screen.dart
  lib/views/profile/settings/settings_view.dart
  lib/views/profile/wishlist.dart
  lib/views/search_view.dart
  lib/views/terms_conditions_view.dart
  lib/views/unknown_view.dart
  lib/widgets/address_text_field.dart
  lib/widgets/back_button.dart
  lib/widgets/bottom_nav_bar.dart
  lib/widgets/drawer_item.dart
  lib/widgets/payment/cart_item.dart
  lib/widgets/payment/order_item.dart
  lib/widgets/payment/payment_successful.dart
  lib/widgets/payment/payment_window.dart
  lib/widgets/product/product_card.dart
  lib/widgets/product/product_page.dart
  lib/widgets/retro_button.dart
  lib/widgets/search_bar.dart
  pubspec.yaml
  test/widget_test.dart
Labels: GSSOC21, Level2

#210 modified contributng.md
  CONTRIBUTING.md
Labels: GSSOC21, Level1

#211 Fixes #49
  lib/services/remote_config.dart
  lib/views/search_view.dart
  pubspec.yaml
Labels: GSSOC21, Level2

#213 Fixes #39
  lib/views/profile/profile_view.dart
Labels: GSSOC21, Level1

#212 displayed user data
  lib/dashboard.dart
  lib/main.dart
  lib/model/user_model.dart
  lib/services/db_userdata.dart
  lib/views/home_view.dart
  lib/views/profile/profile_view.dart
Labels: GSSOC21, Level2
